### ISSUE TITLE
Tkhtml1 garbles when scrolling on OS X

### ISSUE THREAD

**Issue by codebykevin** [wjoye/tkhtml1#1]
On OS X 10.11, using Tcl/Tk 8.6.5, the help viewer in SAO DS9 does not display text correctly. In fact, the text is highly garbled when the help viewer is scrolled. Please see screen shot. 
![screen shot 2016-07-23 at 11 42 40 pm](https://cloud.githubusercontent.com/assets/1253295/17081665/57b7539e-512f-11e6-9c11-a9362f10eb59.png)

**Comment by wjoye** [comment]
fixed

**Comment by codebykevin** [comment]
Thank you. Will test asp. 

Any chance DS9 can upgrade to Tcl/Tk 8.6.5 in the next beta?  The Mac Aqua build of DS9 has some redraw glitches that are fixed in 8.6.5.

**Comment by wjoye** [comment]
will do. next beta.
